// Auto-generated from git commits by scripts/generate-changelog.js
// Do not edit manually - run 'npm run generate:changelog' to update

export interface ChangelogChange {
  hash: string;
  type: "feature" | "fix" | "improvement";
  label: string;
  title: string;
  description: string;
}

export interface ChangelogEntry {
  date: string;
  changes: ChangelogChange[];
}

export const changelog: ChangelogEntry[] = [
  {
    date: "October 5, 2025",
    changes: [
      {
        hash: "7ebb133",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add changelog page at /changelog",
        description: "add changelog page at /changelog",
      },
      {
        hash: "1ed35ea",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Simplify level display styling",
        description: "simplify level display styling",
      },
      {
        hash: "0a50a8d",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Move level display to right of avatar with brackets",
        description: "move level display to right of avatar with brackets",
      },
      {
        hash: "8dcfa34",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Show user level beside avatar in navigation",
        description: "show user level beside avatar in navigation",
      },
      {
        hash: "18eecef",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Replace profile button with avatar and add account management",
        description: "replace profile button with avatar and add account management",
      },
      {
        hash: "5c259c3",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Separate build configs for web and Tauri",
        description: "separate build configs for web and Tauri",
      },
      {
        hash: "0b0a85e",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add download page and fix TypeScript errors",
        description: "add download page and fix TypeScript errors",
      },
      {
        hash: "1da11ad",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add Tauri for Mac app packaging",
        description: "add Tauri for Mac app packaging",
      },
      {
        hash: "6cafd2c",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Remove Clerk username sync that was causing 403 errors",
        description: "remove Clerk username sync that was causing 403 errors",
      },
      {
        hash: "be639fe",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Improve browser notifications and remove Framer Motion warning",
        description: "improve browser notifications and remove Framer Motion warning",
      },
      {
        hash: "af607cd",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add notification permission button and better debugging",
        description: "add notification permission button and better debugging",
      },
      {
        hash: "7e9fc37",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Add missing useCallback import",
        description: "add missing useCallback import",
      },
      {
        hash: "280c4db",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add completion sound and browser notifications",
        description: "add completion sound and browser notifications",
      },
      {
        hash: "1aadc69",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add debug mode and update pomos tracking",
        description: "add debug mode and update pomos tracking",
      },
      {
        hash: "29be896",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Maintain Reset button and show pause state clearly",
        description: "maintain Reset button and show pause state clearly",
      },
      {
        hash: "0e74d97",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Transform Start button into Pause when timer runs",
        description: "transform Start button into Pause when timer runs",
      },
      {
        hash: "bc79e35",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Center button content properly",
        description: "center button content properly",
      },
      {
        hash: "43ac466",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Move SPACE hint inside Start button",
        description: "move SPACE hint inside Start button",
      },
      {
        hash: "bd079e0",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Replace text hint with skeuomorphic spacebar visual",
        description: "replace text hint with skeuomorphic spacebar visual",
      },
      {
        hash: "68866e0",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Cleaner button layout with progressive disclosure",
        description: "cleaner button layout with progressive disclosure",
      },
      {
        hash: "b5260cd",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Enlarge start button and add space bar keyboard shortcut",
        description: "enlarge start button and add space bar keyboard shortcut",
      },
      {
        hash: "ae0232b",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Combine profile header and level cards into one",
        description: "combine profile header and level cards into one",
      },
      {
        hash: "b28be40",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Correct level thresholds and add Pokemon-style XP bar",
        description: "correct level thresholds and add Pokemon-style XP bar",
      },
      {
        hash: "dfca474",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Position current pomos marker at exact location on progress bar",
        description: "position current pomos marker at exact location on progress bar",
      },
      {
        hash: "d72b3ee",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add linear range labels to level progress bar",
        description: "add linear range labels to level progress bar",
      },
      {
        hash: "68e9342",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add exponential leveling system to profile",
        description: "add exponential leveling system to profile",
      },
      {
        hash: "94f95c1",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Reduce activity heatmap to show last 8 weeks instead of full year",
        description: "reduce activity heatmap to show last 8 weeks instead of full year",
      },
      {
        hash: "04e2f0a",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add test data seeding and management to profile page",
        description: "add test data seeding and management to profile page",
      },
      {
        hash: "888cfbd",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Add profile page with stats and activity heatmap",
        description: "add profile page with stats and activity heatmap",
      },
      {
        hash: "4e5072d",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Revert to square card container with circular progress inside",
        description: "revert to square card container with circular progress inside",
      },
      {
        hash: "58668dd",
        date: "2025-10-05",
        type: "improvement",
        label: "Improved",
        title: "Revert to original circular design, make it smaller and fix mobile overlaps",
        description: "revert to original circular design, make it smaller and fix mobile overlaps",
      },
      {
        hash: "36f33f2",
        date: "2025-10-05",
        type: "fix",
        label: "Fixed",
        title: "Make progress ring the actual border and add more padding",
        description: "make progress ring the actual border and add more padding",
      },
      {
        hash: "7984846",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Redesign UI with circular container and progress ring border",
        description: "redesign UI with circular container and progress ring border",
      },
      {
        hash: "17402fc",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Sync Convex username to Clerk profile",
        description: "sync Convex username to Clerk profile",
      },
      {
        hash: "7522a46",
        date: "2025-10-05",
        type: "feature",
        label: "New",
        title: "Auto-generate usernames from first/last name",
        description: "auto-generate usernames from first/last name",
      },
    ],
  },
  {
    date: "October 4, 2025",
    changes: [
      {
        hash: "922d8da",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Add Convex auth config for Clerk",
        description: "add Convex auth config for Clerk",
      },
      {
        hash: "67eac64",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Sync local pomodoros to Convex when user signs up",
        description: "sync local pomodoros to Convex when user signs up",
      },
      {
        hash: "ee46dc4",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Custom social button layout - Google full width, Apple/Facebook 50%",
        description: "custom social button layout - Google full width, Apple/Facebook 50%",
      },
      {
        hash: "2775537",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Hide username field and make Google sign-in button prominent",
        description: "hide username field and make Google sign-in button prominent",
      },
      {
        hash: "5479a26",
        date: "2025-10-04",
        type: "fix",
        label: "Fixed",
        title: "Also hide first name and last name labels in signup form",
        description: "also hide first name and last name labels in signup form",
      },
      {
        hash: "d7fc2bc",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Remove first name and last name fields from signup",
        description: "remove first name and last name fields from signup",
      },
      {
        hash: "45739da",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Update auth button to 'Signup / Signin' and default to signup",
        description: "update auth button to 'Signup / Signin' and default to signup",
      },
      {
        hash: "11e05ba",
        date: "2025-10-04",
        type: "improvement",
        label: "Improved",
        title: "Use 24-hour time format in feed",
        description: "use 24-hour time format in feed",
      },
      {
        hash: "e0a76c4",
        date: "2025-10-04",
        type: "improvement",
        label: "Improved",
        title: "Show only focus sessions in feed",
        description: "show only focus sessions in feed",
      },
      {
        hash: "5e913a7",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Add pomodoro session feed",
        description: "add pomodoro session feed",
      },
      {
        hash: "3254692",
        date: "2025-10-04",
        type: "fix",
        label: "Fixed",
        title: "Remove unused useQuery import",
        description: "remove unused useQuery import",
      },
      {
        hash: "88be05e",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Hybrid Convex sync for authenticated users",
        description: "hybrid Convex sync for authenticated users",
      },
      {
        hash: "3d887a7",
        date: "2025-10-04",
        type: "improvement",
        label: "Improved",
        title: "Improve code organization and modularity",
        description: "improve code organization and modularity",
      },
      {
        hash: "9b3aab2",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Make auth optional, add local session storage",
        description: "make auth optional, add local session storage",
      },
      {
        hash: "1905c3a",
        date: "2025-10-04",
        type: "fix",
        label: "Fixed",
        title: "Remove conditional from build step",
        description: "remove conditional from build step",
      },
      {
        hash: "02c85cf",
        date: "2025-10-04",
        type: "improvement",
        label: "Improved",
        title: "Clean CI approach with optional build + setup guide",
        description: "clean CI approach with optional build + setup guide",
      },
      {
        hash: "217ad9b",
        date: "2025-10-04",
        type: "fix",
        label: "Fixed",
        title: "Make Clerk optional for CI builds",
        description: "make Clerk optional for CI builds",
      },
      {
        hash: "4d6941c",
        date: "2025-10-04",
        type: "feature",
        label: "New",
        title: "Secure Convex + Clerk auth with comprehensive tests",
        description: "secure Convex + Clerk auth with comprehensive tests",
      },
    ],
  },
  {
    date: "October 3, 2025",
    changes: [
      {
        hash: "9871df9",
        date: "2025-10-03",
        type: "feature",
        label: "New",
        title: "Cohesive minimal dark theme with slate palette",
        description: "cohesive minimal dark theme with slate palette",
      },
      {
        hash: "31469b7",
        date: "2025-10-03",
        type: "improvement",
        label: "Improved",
        title: "Extract timer logic into useTimer hook",
        description: "extract timer logic into useTimer hook",
      },
      {
        hash: "a8848a4",
        date: "2025-10-03",
        type: "improvement",
        label: "Improved",
        title: "Improve timer implementation and remove duplicate src directory",
        description: "improve timer implementation and remove duplicate src directory",
      },
      {
        hash: "3a845de",
        date: "2025-10-03",
        type: "feature",
        label: "New",
        title: "Add shadcn Progress component",
        description: "add shadcn Progress component",
      },
    ],
  },
];
