name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Prettier (format check)
        run: npm run format:check

      - name: ESLint (no warnings)
        run: npm run lint:strict

      - name: TypeScript
        run: npm run typecheck

      - name: Tests
        run: npm test

      - name: Build
        run: npm run build
        env:
          # Placeholder values for build-time only
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_placeholder
          CLERK_SECRET_KEY: sk_test_placeholder
          NEXT_PUBLIC_CONVEX_URL: https://placeholder.convex.cloud
